export const applicationPage = {
  nationality: 'Indian',
  currentLocation: 'Mumbai',
  category: 'General',
  state: 'Maharashtra',
  city: 'Mumbai',
  elective1: 'MCOM',
  elective2: 'Public Accounting',
  abcId: 'ABC123456',
  debId: 'DEB123456',
  nameAsPerDebId: 'John Doe',
  emailAsPerDebId: 'john@example.com',
  phoneAsPerDebId: '9876543210',
  gender: 'Male',
  dob: '2000-01-01',
  nameAsPerTenth: 'John Doe',
  email: 'qatemp1@yopmail.com',
  phone: '9848901347',
  altPhone: '9812345678',
  scholarshipNote: 'Applied via sports quota',
  physicallyChallenged: true,
  militaryBackground: false,
  otherScholarship: false
};